<Type Name="UnhandledExceptionAction" FullName="System.Activities.UnhandledExceptionAction">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="070ae82d795d2b3a920f23bb6d8e67539cdf87c2" />
    <Meta Name="ms.sourcegitcommit" Value="d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b" />
    <Meta Name="ms.translationtype" Value="MT" />
    <Meta Name="ms.contentlocale" Value="pl-PL" />
    <Meta Name="ms.lasthandoff" Value="04/03/2018" />
    <Meta Name="ms.locfileid" Value="30436968" />
  </Metadata>
  <TypeSignature Language="C#" Value="public enum UnhandledExceptionAction" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi sealed UnhandledExceptionAction extends System.Enum" />
  <TypeSignature Language="DocId" Value="T:System.Activities.UnhandledExceptionAction" />
  <TypeSignature Language="VB.NET" Value="Public Enum UnhandledExceptionAction" />
  <TypeSignature Language="C++ CLI" Value="public enum class UnhandledExceptionAction" />
  <AssemblyInfo>
    <AssemblyName>System.Activities</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Enum</BaseTypeName>
  </Base>
  <Docs>
    <summary>
      <span data-ttu-id="c4864-101">Określa akcję wykonywaną, gdy wyjątek specjalne głównego przepływu pracy.</span>
      <span class="sxs-lookup">
        <span data-stu-id="c4864-101">Specifies the action that occurs when an exception escapes the root of a workflow.</span>
      </span>
    </summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c4864-102"><xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> Funkcja jest wywoływana, jeśli wyjątek specjalne głównego przepływu pracy.</span><span class="sxs-lookup"><span data-stu-id="c4864-102">The <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> function is invoked if an exception escapes the root of the workflow.</span></span> <span data-ttu-id="c4864-103"><xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> Zapewnia dostęp do wyjątku, a także wskaźnik do <xref:System.Activities.Activity> który wygenerowany wyjątek.</span><span class="sxs-lookup"><span data-stu-id="c4864-103">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> provides access to the exception as well as a pointer to the <xref:System.Activities.Activity> that generated the exception.</span></span> <span data-ttu-id="c4864-104">Przerwanie jest domyślną akcję, jeśli nie <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> określono obsługi.</span><span class="sxs-lookup"><span data-stu-id="c4864-104">Terminate is the default action if no <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is specified.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="c4864-105">Poniższy przykład przedstawia wywoływanie przepływu pracy, który zgłasza wyjątek.</span><span class="sxs-lookup"><span data-stu-id="c4864-105">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="c4864-106">Wyjątek jest nieobsługiwany przez przepływ pracy i <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> obsługi jest wywoływany.</span><span class="sxs-lookup"><span data-stu-id="c4864-106">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="c4864-107"><xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> Są kontrolowane w celu podania informacji o wyjątku, a przepływ pracy zostanie zakończony.</span><span class="sxs-lookup"><span data-stu-id="c4864-107">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is terminated.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#6](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#6)]  
  
 ]]></format>
    </remarks>
  </Docs>
  <Members>
    <Member MemberName="Abort">
      <MemberSignature Language="C#" Value="Abort" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Activities.UnhandledExceptionAction Abort = int32(0)" />
      <MemberSignature Language="DocId" Value="F:System.Activities.UnhandledExceptionAction.Abort" />
      <MemberSignature Language="VB.NET" Value="Abort" />
      <MemberSignature Language="C++ CLI" Value="Abort" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Activities.UnhandledExceptionAction</ReturnType>
      </ReturnValue>
      <MemberValue>0</MemberValue>
      <Docs>
        <summary>
          <span data-ttu-id="c4864-108">Określa, że <see cref="T:System.Activities.WorkflowApplication" /> należy przerwać przepływu pracy.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c4864-108">Specifies that the <see cref="T:System.Activities.WorkflowApplication" /> should abort the workflow.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c4864-109">Powoduje to <xref:System.Activities.WorkflowApplication.Aborted%2A> wywoływana po zakończeniu procesu przerwania.</span><span class="sxs-lookup"><span data-stu-id="c4864-109">This results in <xref:System.Activities.WorkflowApplication.Aborted%2A> being called when the abort process is complete.</span></span> <span data-ttu-id="c4864-110">Nieobsługiwany wyjątek jest używany jako z powodu przerwania.</span><span class="sxs-lookup"><span data-stu-id="c4864-110">The unhandled exception is used as the abort reason.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="c4864-111">Poniższy przykład przedstawia wywoływanie przepływu pracy, który zgłasza wyjątek.</span><span class="sxs-lookup"><span data-stu-id="c4864-111">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="c4864-112">Wyjątek jest nieobsługiwany przez przepływ pracy i <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> obsługi jest wywoływany.</span><span class="sxs-lookup"><span data-stu-id="c4864-112">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="c4864-113"><xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> Są kontrolowane w celu podania informacji o wyjątku, a przepływ pracy został przerwany.</span><span class="sxs-lookup"><span data-stu-id="c4864-113">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is aborted.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#7](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#7)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="Cancel">
      <MemberSignature Language="C#" Value="Cancel" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Activities.UnhandledExceptionAction Cancel = int32(1)" />
      <MemberSignature Language="DocId" Value="F:System.Activities.UnhandledExceptionAction.Cancel" />
      <MemberSignature Language="VB.NET" Value="Cancel" />
      <MemberSignature Language="C++ CLI" Value="Cancel" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Activities.UnhandledExceptionAction</ReturnType>
      </ReturnValue>
      <MemberValue>1</MemberValue>
      <Docs>
        <summary>
          <span data-ttu-id="c4864-114">Określa, że <see cref="T:System.Activities.WorkflowApplication" /> należy zaplanować anulowania działania głównego i wznowić wykonywanie.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c4864-114">Specifies that the <see cref="T:System.Activities.WorkflowApplication" /> should schedule the cancellation of the root activity and resume execution.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c4864-115">Powoduje to <xref:System.Activities.WorkflowApplication.Completed%2A> wywoływana po zakończeniu procesu anulowania.</span><span class="sxs-lookup"><span data-stu-id="c4864-115">This results in <xref:System.Activities.WorkflowApplication.Completed%2A> being called when the cancellation process is complete.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="c4864-116">Poniższy przykład przedstawia wywoływanie przepływu pracy, który zgłasza wyjątek.</span><span class="sxs-lookup"><span data-stu-id="c4864-116">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="c4864-117">Wyjątek jest nieobsługiwany przez przepływ pracy i <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> obsługi jest wywoływany.</span><span class="sxs-lookup"><span data-stu-id="c4864-117">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="c4864-118"><xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> Są kontrolowane w celu podania informacji o wyjątku, i przepływu pracy zostało anulowane.</span><span class="sxs-lookup"><span data-stu-id="c4864-118">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is cancelled.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#8](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#8)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="Terminate">
      <MemberSignature Language="C#" Value="Terminate" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype System.Activities.UnhandledExceptionAction Terminate = int32(2)" />
      <MemberSignature Language="DocId" Value="F:System.Activities.UnhandledExceptionAction.Terminate" />
      <MemberSignature Language="VB.NET" Value="Terminate" />
      <MemberSignature Language="C++ CLI" Value="Terminate" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Activities</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Activities.UnhandledExceptionAction</ReturnType>
      </ReturnValue>
      <MemberValue>2</MemberValue>
      <Docs>
        <summary>
          <span data-ttu-id="c4864-119">Określa, że <see cref="T:System.Activities.WorkflowApplication" /> należy zaplanować przerwanie działania głównego i wznowić wykonywanie.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c4864-119">Specifies that the <see cref="T:System.Activities.WorkflowApplication" /> should schedule termination of the root activity and resume execution.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c4864-120">Powoduje to <xref:System.Activities.WorkflowApplication.Completed%2A> wywoływana po zakończeniu procesu zakończenia.</span><span class="sxs-lookup"><span data-stu-id="c4864-120">This results in <xref:System.Activities.WorkflowApplication.Completed%2A> being called when the termination process is complete.</span></span> <span data-ttu-id="c4864-121">Nieobsługiwany wyjątek jest używany jako z powodu zakończenia.</span><span class="sxs-lookup"><span data-stu-id="c4864-121">The unhandled exception is used as the termination reason.</span></span> <span data-ttu-id="c4864-122">Przerwanie jest domyślną akcję, jeśli nie <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> określono obsługi.</span><span class="sxs-lookup"><span data-stu-id="c4864-122">Terminate is the default action if no <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is specified.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="c4864-123">Poniższy przykład przedstawia wywoływanie przepływu pracy, który zgłasza wyjątek.</span><span class="sxs-lookup"><span data-stu-id="c4864-123">The following example invokes a workflow that throws an exception.</span></span> <span data-ttu-id="c4864-124">Wyjątek jest nieobsługiwany przez przepływ pracy i <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> obsługi jest wywoływany.</span><span class="sxs-lookup"><span data-stu-id="c4864-124">The exception is unhandled by the workflow and the <xref:System.Activities.WorkflowApplication.OnUnhandledException%2A> handler is invoked.</span></span> <span data-ttu-id="c4864-125"><xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> Są kontrolowane w celu podania informacji o wyjątku, a przepływ pracy zostanie zakończony.</span><span class="sxs-lookup"><span data-stu-id="c4864-125">The <xref:System.Activities.WorkflowApplicationUnhandledExceptionEventArgs> are inspected to provide information about the exception, and the workflow is terminated.</span></span>  
  
 [!code-csharp[CFX_WorkflowApplicationExample#6](~/samples/snippets/csharp/VS_Snippets_CFX/cfx_workflowapplicationexample/cs/program.cs#6)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>