<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="LinqDataSourceValidationException.xml" source-language="en-US" target-language="pl-PL">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac58ae2ee400046dd5174c6de772663b3c4824cc3c3.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">8ae2ee400046dd5174c6de772663b3c4824cc3c3</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Web.UI.WebControls.LinqDataSourceValidationException">
          <source>Describes an exception that occurred during validation of new or modified values before values are inserted, updated, or deleted by a <ph id="ph1">&lt;see cref="T:System.Web.UI.WebControls.LinqDataSource" /&gt;</ph> control.</source>
          <target state="translated">W tym artykule opisano wyjątek, który wystąpił podczas sprawdzania poprawności nowe lub modyfikować wartości przed wstawiania, zaktualizowane lub usunięte przez wartości <ph id="ph1">&lt;see cref="T:System.Web.UI.WebControls.LinqDataSource" /&gt;</ph> formantu.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.UI.WebControls.LinqDataSourceValidationException">
          <source>The <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException&gt;</ph> class contains type conversion and property setter exceptions.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException&gt;</ph> Klasy zawiera typ konwersji i właściwości metody ustawiającej wyjątków.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.UI.WebControls.LinqDataSourceValidationException">
          <source>All of the exceptions that are thrown during validation are contained in the <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A&gt;</ph> collection.</source>
          <target state="translated">Wszystkie wyjątki, które są zgłoszony podczas sprawdzania poprawności są zawarte w <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A&gt;</ph> kolekcji.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.UI.WebControls.LinqDataSourceValidationException">
          <source>You can retrieve each validation exception by iterating through the <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A&gt;</ph> collection.</source>
          <target state="translated">Każdy wyjątek sprawdzania poprawności można pobrać za iteracja <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A&gt;</ph> kolekcji.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.UI.WebControls.LinqDataSourceValidationException">
          <source>You typically handle exceptions in the <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSource.Updating&gt;</ph>, <ph id="ph2">&lt;xref:System.Web.UI.WebControls.LinqDataSource.Deleting&gt;</ph>, and <ph id="ph3">&lt;xref:System.Web.UI.WebControls.LinqDataSource.Inserting&gt;</ph> events.</source>
          <target state="translated">Zwykle Obsługa wyjątków w <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSource.Updating&gt;</ph>, <ph id="ph2">&lt;xref:System.Web.UI.WebControls.LinqDataSource.Deleting&gt;</ph>, i <ph id="ph3">&lt;xref:System.Web.UI.WebControls.LinqDataSource.Inserting&gt;</ph> zdarzenia.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.UI.WebControls.LinqDataSourceValidationException">
          <source>If a validation exception is thrown, the <ph id="ph1">`Exception`</ph> property of the <ph id="ph2">&lt;xref:System.Web.UI.WebControls.LinqDataSourceUpdateEventArgs&gt;</ph>, <ph id="ph3">&lt;xref:System.Web.UI.WebControls.LinqDataSourceDeleteEventArgs&gt;</ph>, or <ph id="ph4">&lt;xref:System.Web.UI.WebControls.LinqDataSourceInsertEventArgs&gt;</ph> object contains a <ph id="ph5">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException&gt;</ph> object.</source>
          <target state="translated">Jeśli sprawdzanie poprawności wyjątku, <ph id="ph1">`Exception`</ph> właściwość <ph id="ph2">&lt;xref:System.Web.UI.WebControls.LinqDataSourceUpdateEventArgs&gt;</ph>, <ph id="ph3">&lt;xref:System.Web.UI.WebControls.LinqDataSourceDeleteEventArgs&gt;</ph>, lub <ph id="ph4">&lt;xref:System.Web.UI.WebControls.LinqDataSourceInsertEventArgs&gt;</ph> zawiera obiekt <ph id="ph5">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException&gt;</ph> obiektu.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.UI.WebControls.LinqDataSourceValidationException">
          <source>If no exception is thrown, the <ph id="ph1">`Exception`</ph> property contains <ph id="ph2">`null`</ph>.</source>
          <target state="translated">Jeśli nie jest wyjątek <ph id="ph1">`Exception`</ph> zawiera właściwość <ph id="ph2">`null`</ph>.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.UI.WebControls.LinqDataSourceValidationException">
          <source>To handle validation exceptions, create a handler for the <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSource.Updating&gt;</ph>, <ph id="ph2">&lt;xref:System.Web.UI.WebControls.LinqDataSource.Deleting&gt;</ph>, or <ph id="ph3">&lt;xref:System.Web.UI.WebControls.LinqDataSource.Inserting&gt;</ph> event.</source>
          <target state="translated">Do obsługi wyjątków weryfikacji, należy utworzyć programu obsługi dla <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSource.Updating&gt;</ph>, <ph id="ph2">&lt;xref:System.Web.UI.WebControls.LinqDataSource.Deleting&gt;</ph>, lub <ph id="ph3">&lt;xref:System.Web.UI.WebControls.LinqDataSource.Inserting&gt;</ph> zdarzeń.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.UI.WebControls.LinqDataSourceValidationException">
          <source>In the event handler, check whether the <ph id="ph1">`Exception`</ph> property of the event argument class contains a value other than <ph id="ph2">`null`</ph>.</source>
          <target state="translated">W obsłudze zdarzeń, sprawdź, czy <ph id="ph1">`Exception`</ph> właściwość klasy argument zdarzenia zawiera wartości inne niż <ph id="ph2">`null`</ph>.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.UI.WebControls.LinqDataSourceValidationException">
          <source>If the <ph id="ph1">`Exception`</ph> property is not null, one or more validation exceptions were thrown and you can retrieve each validation exception in the <ph id="ph2">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A&gt;</ph> property.</source>
          <target state="translated">Jeśli <ph id="ph1">`Exception`</ph> właściwość nie jest zerowa, co najmniej jeden wyjątek sprawdzania poprawności zostały zgłoszone i mogą pobierać każdym wyjątku weryfikacji <ph id="ph2">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A&gt;</ph> właściwości.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.UI.WebControls.LinqDataSourceValidationException">
          <source>A validation exception can occur if a value does not match the type of the property.</source>
          <target state="translated">Wyjątek do sprawdzania poprawności może wystąpić, jeśli wartość nie jest zgodny z typem właściwości.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.UI.WebControls.LinqDataSourceValidationException">
          <source>For example, trying to update an integer property by using non-numeric characters causes a validation exception.</source>
          <target state="translated">Na przykład próby zaktualizowania właściwość typu integer przy użyciu znaków nienumerycznych powoduje, że wyjątek sprawdzania poprawności.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.UI.WebControls.LinqDataSourceValidationException">
          <source>A LINQ to SQL class can also contain customized validation criteria that make sure that the property contains a value that is within an expected range or pattern.</source>
          <target state="translated">LINQ do SQL klasy może również zawierać kryteria weryfikacji dostosowane upewnij się, że właściwość zawiera wartość, która znajduje się w oczekiwanym zakresem lub wzorzec.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.UI.WebControls.LinqDataSourceValidationException">
          <source>The following example shows an event handler for the <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSource.Updating&gt;</ph> event.</source>
          <target state="translated">W poniższym przykładzie przedstawiono program obsługi zdarzeń dla <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSource.Updating&gt;</ph> zdarzeń.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Web.UI.WebControls.LinqDataSourceValidationException">
          <source>It displays any validation exception messages by using a <ph id="ph1">&lt;xref:System.Web.UI.WebControls.Label&gt;</ph> control.</source>
          <target state="translated">Wyświetla wszystkie komunikaty o wyjątkach weryfikacji przy użyciu <ph id="ph1">&lt;xref:System.Web.UI.WebControls.Label&gt;</ph> formantu.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" uid="T:System.Web.UI.WebControls.LinqDataSourceValidationException">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /&gt;</ph> class.</source>
          <target state="translated">Inicjuje nowe wystąpienie klasy <ph id="ph1">&lt;see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /&gt;</ph> klasy.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /&gt;</ph> class with a system-supplied message that describes the error.</source>
          <target state="translated">Inicjuje nowe wystąpienie klasy <ph id="ph1">&lt;see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /&gt;</ph> używając dostarczany przez system komunikatu opisującego błąd.</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor">
          <source>The system-supplied message that describes the error takes into account the current system culture.</source>
          <target state="translated">Dostarczane przez system komunikatu opisującego błąd bierze pod uwagę bieżące ustawienia kulturowe systemu.</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor">
          <source>The following table shows the initial property values for an instance of the <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException&gt;</ph> class.</source>
          <target state="translated">W poniższej tabeli przedstawiono początkowe wartości właściwości dla wystąpienia <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException&gt;</ph> klasy.</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor">
          <source>Property</source>
          <target state="translated">Właściwość</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor">
          <source>Value</source>
          <target state="translated">Wartość</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor">
          <source><ph id="ph1">`null`</ph>.</source>
          <target state="translated"><ph id="ph1">`null`</ph>.</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor">
          <source>A system-supplied localized description.</source>
          <target state="translated">Zlokalizowany opis dostarczany przez system.</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String)">
          <source>The message that describes the error.</source>
          <target state="translated">Komunikat, który opisuje błąd.</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /&gt;</ph> class with a specified message that describes the error.</source>
          <target state="translated">Inicjuje nowe wystąpienie klasy <ph id="ph1">&lt;see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /&gt;</ph> klasy z określony komunikat zawierający opis błędu.</target>       </trans-unit>
        <trans-unit id="126" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String)">
          <source>The following table shows the initial property values for an instance of the <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException&gt;</ph> class.</source>
          <target state="translated">W poniższej tabeli przedstawiono początkowe wartości właściwości dla wystąpienia <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException&gt;</ph> klasy.</target>       </trans-unit>
        <trans-unit id="127" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String)">
          <source>Property</source>
          <target state="translated">Właściwość</target>       </trans-unit>
        <trans-unit id="128" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String)">
          <source>Value</source>
          <target state="translated">Wartość</target>       </trans-unit>
        <trans-unit id="129" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String)">
          <source><ph id="ph1">`null`</ph>.</source>
          <target state="translated"><ph id="ph1">`null`</ph>.</target>       </trans-unit>
        <trans-unit id="130" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String)">
          <source>The error message string specified in <ph id="ph1">`message`</ph>.</source>
          <target state="translated">Ciąg z komunikatem o określonych w <ph id="ph1">`message`</ph>.</target>       </trans-unit>
        <trans-unit id="131" translate="yes" xml:space="preserve" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The object that holds the serialized object data.</source>
          <target state="translated">Obiekt zawierający dane serializowanego obiektu.</target>       </trans-unit>
        <trans-unit id="132" translate="yes" xml:space="preserve" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Context information about the source or destination.</source>
          <target state="translated">Informacje kontekstowe o źródle lub miejscu docelowym.</target>       </trans-unit>
        <trans-unit id="133" translate="yes" xml:space="preserve" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /&gt;</ph> class with serialized data.</source>
          <target state="translated">Inicjuje nowe wystąpienie klasy <ph id="ph1">&lt;see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /&gt;</ph> z zserializowanymi danymi.</target>       </trans-unit>
        <trans-unit id="134" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>This constructor is called during deserialization to reconstitute the exception object that is transmitted over a stream.</source>
          <target state="translated">Ten konstruktor jest wywoływana podczas deserializacji do odtworzenia obiekt wyjątku przesyłanych przez strumień.</target>       </trans-unit>
        <trans-unit id="135" translate="yes" xml:space="preserve" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String,System.Collections.Generic.IDictionary{System.String,System.Exception})">
          <source>The message that describes the error.</source>
          <target state="translated">Komunikat, który opisuje błąd.</target>       </trans-unit>
        <trans-unit id="136" translate="yes" xml:space="preserve" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String,System.Collections.Generic.IDictionary{System.String,System.Exception})">
          <source>The collection of validation exceptions.</source>
          <target state="translated">Kolekcja wyjątków sprawdzania poprawności.</target>       </trans-unit>
        <trans-unit id="137" translate="yes" xml:space="preserve" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String,System.Collections.Generic.IDictionary{System.String,System.Exception})">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /&gt;</ph> class with a specified message that describes the error, and a collection of references to inner exceptions.</source>
          <target state="translated">Inicjuje nowe wystąpienie klasy <ph id="ph1">&lt;see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /&gt;</ph> klasy z określony komunikat zawierający opis błędu, a kolekcja odwołań do wyjątków wewnętrznych.</target>       </trans-unit>
        <trans-unit id="138" translate="yes" xml:space="preserve" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String,System.Exception)">
          <source>The message that describes the error.</source>
          <target state="translated">Komunikat, który opisuje błąd.</target>       </trans-unit>
        <trans-unit id="139" translate="yes" xml:space="preserve" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String,System.Exception)">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">Wyjątek, który jest przyczyną bieżącego wyjątku.</target>       </trans-unit>
        <trans-unit id="140" translate="yes" xml:space="preserve" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /&gt;</ph> class with a specified error message and a reference to the inner exception.</source>
          <target state="translated">Inicjuje nowe wystąpienie klasy <ph id="ph1">&lt;see cref="T:System.Web.UI.WebControls.LinqDataSourceValidationException" /&gt;</ph> z określonego komunikatu o błędzie i odwołania do wyjątek wewnętrzny.</target>       </trans-unit>
        <trans-unit id="141" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.#ctor(System.String,System.Exception)">
          <source>You typically will not use this constructor because validation exceptions are stored in the <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A&gt;</ph> property, not the <ph id="ph2">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.</source>
          <target state="translated">Zwykle nie użyjesz tego konstruktora ponieważ wyjątki poprawności są przechowywane w <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A&gt;</ph> właściwości, nie <ph id="ph2">&lt;xref:System.Exception.InnerException%2A&gt;</ph> właściwości.</target>       </trans-unit>
        <trans-unit id="142" translate="yes" xml:space="preserve" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The object that holds the serialized object data for the exception that is being thrown.</source>
          <target state="translated">Obiekt przechowujący dane Zserializowany obiekt, który został zgłoszony wyjątek.</target>       </trans-unit>
        <trans-unit id="143" translate="yes" xml:space="preserve" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Context information about the source or destination.</source>
          <target state="translated">Informacje kontekstowe o źródle lub miejscu docelowym.</target>       </trans-unit>
        <trans-unit id="144" translate="yes" xml:space="preserve" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Gets information about the exception and adds it to the <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> object.</source>
          <target state="translated">Pobiera informacje o wyjątku i dodaje go do <ph id="ph1">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> obiektu.</target>       </trans-unit>
        <trans-unit id="145" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData%2A&gt;</ph> method adds information about the exception to the <ph id="ph2">&lt;xref:System.Runtime.Serialization.SerializationInfo&gt;</ph> object that is targeted for serialization.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData%2A&gt;</ph> Metody dodaje informacje o wyjątku, aby <ph id="ph2">&lt;xref:System.Runtime.Serialization.SerializationInfo&gt;</ph> obiekt, który jest przeznaczony dla serializacji.</target>       </trans-unit>
        <trans-unit id="146" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Web.UI.WebControls.LinqDataSourceValidationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>During deserialization, the exception is reconstituted from the <ph id="ph1">&lt;xref:System.Runtime.Serialization.SerializationInfo&gt;</ph> that is transmitted over the stream.</source>
          <target state="translated">Podczas deserializacji, wyjątek jest odtworzonych z <ph id="ph1">&lt;xref:System.Runtime.Serialization.SerializationInfo&gt;</ph> który są przesyłane za pośrednictwem strumienia.</target>       </trans-unit>
        <trans-unit id="147" translate="yes" xml:space="preserve" uid="P:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions">
          <source>Gets one or more exceptions that occurred when new or modified data was being validated.</source>
          <target state="translated">Pobiera co najmniej jeden wyjątek, które podczas weryfikacji nowe lub zmodyfikowane dane.</target>       </trans-unit>
        <trans-unit id="148" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions">
          <source>A collection that contains the exceptions.</source>
          <target state="translated">Kolekcja, która zawiera wyłączenia.</target>       </trans-unit>
        <trans-unit id="149" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions">
          <source>The <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A&gt;</ph> collection contains all the validation exceptions that were thrown during data validation before an update, insert, or delete operation.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions%2A&gt;</ph> Kolekcja zawiera wszystkie wyjątki poprawności, które zostały zgłoszone podczas sprawdzania poprawności danych przed aktualizacją, Wstaw lub operacji usuwania.</target>       </trans-unit>
        <trans-unit id="150" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions">
          <source>A validation exception can occur if a value does not match the type of the property.</source>
          <target state="translated">Wyjątek do sprawdzania poprawności może wystąpić, jeśli wartość nie jest zgodny z typem właściwości.</target>       </trans-unit>
        <trans-unit id="151" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions">
          <source>For example, if you try to update an integer property by using non-numeric characters, a validation exception is thrown.</source>
          <target state="translated">Na przykład jeśli użytkownik próbuje zaktualizować właściwość typu integer przy użyciu znaków innych niż alfanumeryczne, sprawdzanie poprawności wyjątku.</target>       </trans-unit>
        <trans-unit id="152" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions">
          <source>A LINQ to SQL class can also contain customized validation criteria that make sure that the property contains a value that is within an expected range or pattern.</source>
          <target state="translated">LINQ do SQL klasy może również zawierać kryteria weryfikacji dostosowane upewnij się, że właściwość zawiera wartość, która znajduje się w oczekiwanym zakresem lub wzorzec.</target>       </trans-unit>
        <trans-unit id="153" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions">
          <source>The following example shows an event handler for the <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSource.Updating&gt;</ph> event.</source>
          <target state="translated">W poniższym przykładzie przedstawiono program obsługi zdarzeń dla <ph id="ph1">&lt;xref:System.Web.UI.WebControls.LinqDataSource.Updating&gt;</ph> zdarzeń.</target>       </trans-unit>
        <trans-unit id="154" translate="yes" xml:space="preserve" extradata="MT" uid="P:System.Web.UI.WebControls.LinqDataSourceValidationException.InnerExceptions">
          <source>It displays any validation exception messages by using a <ph id="ph1">&lt;xref:System.Web.UI.WebControls.Label&gt;</ph> control.</source>
          <target state="translated">Wyświetla wszystkie komunikaty o wyjątkach weryfikacji przy użyciu <ph id="ph1">&lt;xref:System.Web.UI.WebControls.Label&gt;</ph> formantu.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>